// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source=processor.go -destination=mock/processor_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockThumbnailProcessor is a mock of ThumbnailProcessor interface.
type MockThumbnailProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockThumbnailProcessorMockRecorder
	isgomock struct{}
}

// MockThumbnailProcessorMockRecorder is the mock recorder for MockThumbnailProcessor.
type MockThumbnailProcessorMockRecorder struct {
	mock *MockThumbnailProcessor
}

// NewMockThumbnailProcessor creates a new mock instance.
func NewMockThumbnailProcessor(ctrl *gomock.Controller) *MockThumbnailProcessor {
	mock := &MockThumbnailProcessor{ctrl: ctrl}
	mock.recorder = &MockThumbnailProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThumbnailProcessor) EXPECT() *MockThumbnailProcessorMockRecorder {
	return m.recorder
}

// GenerateThumbnail mocks base method.
func (m *MockThumbnailProcessor) GenerateThumbnail(ctx context.Context, inputPath, outputPath string, duration float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateThumbnail", ctx, inputPath, outputPath, duration)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateThumbnail indicates an expected call of GenerateThumbnail.
func (mr *MockThumbnailProcessorMockRecorder) GenerateThumbnail(ctx, inputPath, outputPath, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateThumbnail", reflect.TypeOf((*MockThumbnailProcessor)(nil).GenerateThumbnail), ctx, inputPath, outputPath, duration)
}

// GetDuration mocks base method.
func (m *MockThumbnailProcessor) GetDuration(ctx context.Context, inputPath string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDuration", ctx, inputPath)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDuration indicates an expected call of GetDuration.
func (mr *MockThumbnailProcessorMockRecorder) GetDuration(ctx, inputPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDuration", reflect.TypeOf((*MockThumbnailProcessor)(nil).GetDuration), ctx, inputPath)
}
